### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by pawelwoj** [ryan-roemer/sphinx-bootstrap-theme#220] opened 2021-11-29 19:12 UTC
See:

http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html

**Comment by ryan-roemer** [comment] 2021-11-29 19:35
Looks like a duplicate of https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/213

@pawelwoj can you test out that PR and see if it resolves the issue for you?

**Comment by pawelwoj** [comment] 2021-12-02 14:48
I tried the search box on your demo page which uses sphinx-bootstrap-theme and it doesn't work for me (searching is suspended):

http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html

I have the same problem with my page that also uses  sphinx-bootstrap-theme. I didn't try fix #213, but I don't get the error message.

**Comment by ryan-roemer** [comment] 2021-12-02 14:58
Yeah, the demo page isn't updated.

I didn't quite follow -- did #213 work for you when installed locally?

**Comment by pawelwoj** [comment] 2021-12-02 15:21
I haven’t installed #213 yet.

**Closed** 2022-01-24 18:55 UTC
Labels: bug
