### ISSUE TITLE
Python 3.6 support seems borked

### ISSUE THREAD

**Issue by allanice001** [ryan-roemer/sphinx-bootstrap-theme#165] opened 2017-10-11 01:50 UTC
Specifically when trying to use this theme, i receive the following error:
I've ruled out sphinx, by using sphinx_rtd_theme and that works.
 
```
Exception occurred:
  File "/Users/user/.virtualenvs/gpug/bin/../lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
The full traceback has been saved in /var/folders/qc/v4gd3rhs73nd23b5y55mzvkc0000gn/T/sphinx-err-fayk1cfo.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

Content of the log file:
```
# Sphinx version: 1.5.2
# Python version: 3.6.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/gpug/lib/python3.6/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/user/.virtualenvs/gpug/lib/python3.6/site-packages/sphinx/application.py", line 244, in __init__
    self._init_builder(self.buildername)
  File "/Users/user/.virtualenvs/gpug/lib/python3.6/site-packages/sphinx/application.py", line 314, in _init_builder
    self.builder = builderclass(self)
  File "/Users/user/.virtualenvs/gpug/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 87, in __init__
    self.init()
  File "/Users/user/.virtualenvs/gpug/lib/python3.6/site-packages/sphinx/builders/html.py", line 113, in init
    self.init_templates()
  File "/Users/user/.virtualenvs/gpug/lib/python3.6/site-packages/sphinx/builders/html.py", line 147, in init_templates
    warn=self.warn)
  File "/Users/user/.virtualenvs/gpug/lib/python3.6/site-packages/sphinx/theming.py", line 46, in init_themes
    themedir = path.join(confdir, themedir)
  File "/Users/user/.virtualenvs/gpug/bin/../lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
 File "/Users/user/.virtualenvs/gpug/bin/../lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
```

**Comment by ryan-roemer** [comment] 2017-10-11 03:46
If you can create a minimal repository that reproduces the error with installation and steps to produce the error, I'll take a look at it. Thanks!

**Comment by svenevs** [comment] 2017-10-11 04:19
> TypeError: join() argument must be str or bytes, not 'list'

I'm 95% certain this is a problem with your `conf.py`'s `html_theme_path` :wink:

For `sphinx_rtd_theme`:

```py
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
#                 ^                                      ^
```

They return a string, and you must put it in a list.

For `sphinx_bootstrap_theme`:

```
import sphinx_bootstrap_theme
html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
```

A list is already returned.  You probably have

```
html_theme_path = [sphinx_bootstrap_theme.get_html_theme_path()]
#                 X                                            X
```

which would cause the error you are seeing, since Sphinx will try and `join()` on each element in `html_theme_path`.

**Comment by svenevs** [comment] 2017-12-02 22:54
@allanice001 were you able to get things working / can we close this issue?

**Comment by svenevs** [comment] 2018-03-09 18:38
Closing this issue as it appears to be resolved.  Please post back if it is not.

**Closed by svenevs** 2018-03-09 18:38 UTC
